"""Submit the site's URLs to IndexNow (Bing / Yandex / Seznam / Naver) instantly.

Run on the server after a content deploy (the key file is served from the build):

    python3 backend/scripts/indexnow_ping.py [sitemap_path]

Key hosted at https://astrolab.nikam.dev/<KEY>.txt (file in frontend/static/, so
it survives every deploy). Because the key is at the HOST ROOT, IndexNow accepts
all astrolab.nikam.dev URLs — we submit the Journal URLs from the sitemap here
(the app pages are also covered but the Journal is what changes on autopost).
"""
from __future__ import annotations

import json
import re
import sys
import urllib.error
import urllib.request

HOST = "astrolab.nikam.dev"
KEY = "6bbe9b3a02d8b6c233a06ba742d41e67"
KEY_LOCATION = f"https://{HOST}/{KEY}.txt"
SITEMAP = sys.argv[1] if len(sys.argv) > 1 else "/opt/astrolab/frontend/build/client/sitemap.xml"
PREFIX = f"https://{HOST}/blog/"


def main() -> int:
    try:
        with open(SITEMAP, encoding="utf-8") as fh:
            xml = fh.read()
    except FileNotFoundError:
        # sitemap.xml is generated by the SvelteKit route, not a static file — fall
        # back to fetching it live.
        with urllib.request.urlopen(f"https://{HOST}/sitemap.xml", timeout=20) as r:
            xml = r.read().decode("utf-8")
    urls = sorted({u for u in re.findall(r"<loc>([^<]+)</loc>", xml) if u.startswith(PREFIX)})
    if not urls:
        print("no /blog/ urls found")
        return 1
    payload = {"host": HOST, "key": KEY, "keyLocation": KEY_LOCATION, "urlList": urls}
    req = urllib.request.Request(
        "https://api.indexnow.org/indexnow",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json; charset=utf-8"},
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            print(f"IndexNow: {r.status} for {len(urls)} urls")
        return 0
    except urllib.error.HTTPError as e:
        print(f"IndexNow HTTP {e.code}: {e.read().decode('utf-8', 'ignore')[:200]}")
        return 0  # non-fatal — indexing is best-effort
    except Exception as e:  # noqa: BLE001
        print(f"IndexNow error: {e}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
