"""Submit the site's Journal URLs to IndexNow (Bing / Yandex / Seznam / Naver) instantly.

Run on the server after a content deploy (the key file is served from the build):

    python3 backend/scripts/indexnow_ping.py [sitemap_path]

Key hosted at https://astrolab.nikam.dev/<KEY>.txt (file in frontend/static/, so
it survives every deploy). Because the key is at the HOST ROOT, IndexNow accepts
all astrolab.nikam.dev URLs — we submit the Journal URLs, which is what changes
on autopost.

URLs come from the local blog manifest (frontend/static/blog/index.json), so this
works inside the autopost clone with no network read and no dependency on the live
sitemap: that sitemap is generated by a SvelteKit route (no static file in this
clone), and fetching https://astrolab.nikam.dev/sitemap.xml from the server got a
403 from Cloudflare on every scheduled run. Pass a sitemap path as an argument to
submit whatever it lists instead.
"""
from __future__ import annotations

import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

HOST = "astrolab.nikam.dev"
KEY = "6bbe9b3a02d8b6c233a06ba742d41e67"
KEY_LOCATION = f"https://{HOST}/{KEY}.txt"
ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "frontend" / "static" / "blog" / "index.json"
PREFIX = f"https://{HOST}/blog/"


def _from_manifest() -> list[str]:
    """Every locale URL of every published article, plus the Journal index."""
    articles = json.loads(MANIFEST.read_text("utf-8"))
    urls = {f"https://{HOST}/blog/"}
    for art in articles:
        for loc in art.get("i18n", {}).values():
            url = loc.get("url")
            if url:
                urls.add(f"https://{HOST}{url}")
    return sorted(urls)


def _from_sitemap(path: str) -> list[str]:
    xml = Path(path).read_text("utf-8")
    return sorted({u for u in re.findall(r"<loc>([^<]+)</loc>", xml) if u.startswith(PREFIX)})


def main() -> int:
    try:
        urls = _from_sitemap(sys.argv[1]) if len(sys.argv) > 1 else _from_manifest()
    except (OSError, ValueError) as e:
        print(f"IndexNow: cannot read URL source: {e}")
        return 0  # best-effort — never fail a publish over indexing
    if not urls:
        print("no /blog/ urls found")
        return 0
    payload = {"host": HOST, "key": KEY, "keyLocation": KEY_LOCATION, "urlList": urls}
    req = urllib.request.Request(
        "https://api.indexnow.org/indexnow",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json; charset=utf-8"},
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            print(f"IndexNow: {r.status} for {len(urls)} urls")
        return 0
    except urllib.error.HTTPError as e:
        print(f"IndexNow HTTP {e.code}: {e.read().decode('utf-8', 'ignore')[:200]}")
        return 0  # non-fatal — indexing is best-effort
    except Exception as e:  # noqa: BLE001
        print(f"IndexNow error: {e}")
        return 0


if __name__ == "__main__":
    sys.exit(main())
