"""Seed US salary/demand facts into occupation_country from seed/facts_us.json.

    python -m scripts.seed_facts [--file seed/facts_us.json]

Additive, idempotent, country-scoped (US only — never touches RU facts). The
numbers are real BLS OEWS national wages (generated by scripts.fetch_us_facts);
provenance is recorded via a data_sources row. Upserts by (occupation, country)
so re-running just refreshes. confidence stays 'estimate' — a national wage
range is honestly an estimate for any one person (DESIGN-EN EN-3).
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as dt
import json
from pathlib import Path

from app.db import SessionLocal
from app.models import DataSource, Occupation, OccupationCountry
from sqlalchemy import select

DEFAULT_SEED = Path(__file__).resolve().parent.parent / "seed" / "facts_us.json"


async def run(seed_path: Path) -> None:
    data = json.loads(seed_path.read_text("utf-8"))
    country = data["country"]
    # Provenance + reference date come from the file (US=BLS OEWS, RU=Rosstat),
    # with BLS defaults for backward compatibility.
    src_key = data.get("source_key", "bls-oews")
    src_name = data.get("source_name", "Public domain (U.S. Government work)")
    src_url = data.get("source_url", "https://www.bls.gov/oes/")
    as_of = dt.date.fromisoformat(data.get("as_of_date", "2024-05-01"))

    async with SessionLocal() as s:
        src = (
            await s.execute(select(DataSource).where(DataSource.name == src_key))
        ).scalars().first()
        if src is None:
            src = DataSource(name=src_key, license=src_name[:128], url=src_url)
            s.add(src)
            await s.flush()
        else:
            src.license = src_name[:128]
            src.url = src_url

        occ_by_slug = {
            o.slug: o.id for o in (await s.execute(select(Occupation))).scalars().all()
        }

        n_up = 0
        missing: list[str] = []
        for fact in data["facts"]:
            oid = occ_by_slug.get(fact["slug"])
            if oid is None:
                missing.append(fact["slug"])
                continue
            row = (
                await s.execute(
                    select(OccupationCountry).where(
                        OccupationCountry.occupation_id == oid,
                        OccupationCountry.country == country,
                    )
                )
            ).scalars().first()
            if row is None:
                row = OccupationCountry(occupation_id=oid, country=country)
                s.add(row)
            row.salary_low = fact["salary_low"]
            row.salary_high = fact["salary_high"]
            row.currency = fact["currency"]
            row.demand_note = fact.get("demand_note")
            row.confidence = "estimate"
            row.source_id = src.id
            row.as_of_date = as_of
            n_up += 1

        await s.commit()
        print(f"[seed_facts] {country}: upserted {n_up} facts")
        if missing:
            print(f"[seed_facts] no occupation for: {', '.join(missing)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", default=str(DEFAULT_SEED))
    args = ap.parse_args()
    asyncio.run(run(Path(args.file)))


if __name__ == "__main__":
    main()
