"""Seed US salary/demand facts into occupation_country from seed/facts_us.json.

    python -m scripts.seed_facts [--file seed/facts_us.json]

Additive, idempotent, country-scoped (US only — never touches RU facts). The
numbers are real BLS OEWS national wages (generated by scripts.fetch_us_facts);
provenance is recorded via a data_sources row. Upserts by (occupation, country)
so re-running just refreshes. confidence stays 'estimate' — a national wage
range is honestly an estimate for any one person (DESIGN-EN EN-3).
"""

from __future__ import annotations

import argparse
import asyncio
import datetime as dt
import json
from pathlib import Path

from app.db import SessionLocal
from app.models import DataSource, Occupation, OccupationCountry
from sqlalchemy import select

DEFAULT_SEED = Path(__file__).resolve().parent.parent / "seed" / "facts_us.json"
AS_OF_DATE = dt.date(2024, 5, 1)  # OEWS May 2024 reference period


async def run(seed_path: Path) -> None:
    data = json.loads(seed_path.read_text("utf-8"))
    country = data["country"]

    async with SessionLocal() as s:
        src = (
            await s.execute(select(DataSource).where(DataSource.name == "bls-oews"))
        ).scalars().first()
        if src is None:
            src = DataSource(
                name="bls-oews",
                license="Public domain (U.S. Government work)",
                url="https://www.bls.gov/oes/",
            )
            s.add(src)
            await s.flush()

        occ_by_slug = {
            o.slug: o.id for o in (await s.execute(select(Occupation))).scalars().all()
        }

        n_up = 0
        missing: list[str] = []
        for fact in data["facts"]:
            oid = occ_by_slug.get(fact["slug"])
            if oid is None:
                missing.append(fact["slug"])
                continue
            row = (
                await s.execute(
                    select(OccupationCountry).where(
                        OccupationCountry.occupation_id == oid,
                        OccupationCountry.country == country,
                    )
                )
            ).scalars().first()
            if row is None:
                row = OccupationCountry(occupation_id=oid, country=country)
                s.add(row)
            row.salary_low = fact["salary_low"]
            row.salary_high = fact["salary_high"]
            row.currency = fact["currency"]
            row.demand_note = fact.get("demand_note")
            row.confidence = "estimate"
            row.source_id = src.id
            row.as_of_date = AS_OF_DATE
            n_up += 1

        await s.commit()
        print(f"[seed_facts] {country}: upserted {n_up} facts")
        if missing:
            print(f"[seed_facts] no occupation for: {', '.join(missing)}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--file", default=str(DEFAULT_SEED))
    args = ap.parse_args()
    asyncio.run(run(Path(args.file)))


if __name__ == "__main__":
    main()
